# Generated by Django 2.2.6 on 2020-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='chead0',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='chead1',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='chead2',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
